### PR TITLE
Fix/osx10.9

### PR DESCRIPTION
**Pull request by jakirkham**
Carsten,

Please find included the updated pull request. I have been trying to integrate matplotlib, iPython, etc. for my own use and eventually for others.

In the process of trying to get them to work, I noticed a few more issues. Most of them are minor like a missing include. Some of them are more serious like including the system Python path in the buildem Python path.

Let me know if you have comments, questions, or fixes.

-- John

### CODE REVIEW

**Comment by chaubold** [comment]
Thanks John! First part of my reply..:

I never noticed that the system python path was included in BUILDEM_PYTHON_PATH, but this might be why I had to add the buildem python path to the configure / build commands for several python packages? (See 056aa21e4ac307b913d3103f8c3a06ea381dd313, b72b9a4e642d1c8912dcfbf40666d02ec0f26458)
I'll have a look.

**Comment by chaubold** [comment]
I find it very disturbing that apparently everybody using buildem on Macs encounters different build errors. The Qt4 Xarch_x86_64 flag did not cause any problems on my machine, and the download links for mpfr and nose worked fine, too.

...rebuilding with your patches to check for new errors on my side...

**Comment by jakirkham** [comment]
Sure. Let me know if you have more questions/thoughts.

Possibly, I didn't notice this until I tried installing matplotlib and had clashes over a system copy that was already installed. It would be worth experimenting.

It looks like it does something similar for other OSes in the file being patched. Maybe they should be commented/removed too? I figured we shouldn't worry about until we start merging back into master.

**Comment by jakirkham** [comment]
There use to be a flag that would specify the architecture of the machine for the Mac gcc. It seems Qt's usage is more consistent with that flag. I believe it was called "-arch". Not positive though.

I didn't know this until recently. However, downloads are stored here ( https://github.com/janelia-flyem/janelia-flyem.github.com ) in the downloads folder. This means that all links are ignored unless a FORCE option is added to external_source.

That being said the mpfr site updated to version 3.1.2, which broke that link to the previous version. They don't seem to keep old copies from what I could tell. So, I added a different one that goes to a GNU FTP site that we have used elsewhere.

Similar situation with nose. If it ever tried to download from the old link, there would be trouble. However, it uses the downloads folder.

Everything should be included in the downloads folder as Stuart kindly added them. So, removing the FORCE option from external_source calls that still use it would be wise.

Also, mpfr had a --with-gmp flag. It probably wasn't necessary as we specified the path. However, I added it for good measure. I think it did build on my machine without it though.

Let me know if you run into any more thoughts, questions, or issues.

**Comment by chaubold** [comment]
For me compilation fails here:

```
[ 55%] Performing build step for 'openblas-git'
make[4]: warning: -jN forced in submake: disabling jobserver mode.
...
make[4]: warning: -jN forced in submake: disabling jobserver mode.
Undefined symbols for architecture x86_64:
  "_LAPACKE_cbbcsd", referenced from:
     -exported_symbol[s_list] command line option
... many more of those
  "_sgemm_incopy", referenced from:
      _sgemm_tn in libopenblas_sandybridgep-r0.2.8.a(sgemm_tn.o)
      _sgemm_tt in libopenblas_sandybridgep-r0.2.8.a(sgemm_tt.o)
      _strmm_LTUU in libopenblas_sandybridgep-r0.2.8.a(strmm_LTUU.o)
      _strmm_LTUN in libopenblas_sandybridgep-r0.2.8.a(strmm_LTUN.o)
      _strmm_LTLU in libopenblas_sandybridgep-r0.2.8.a(strmm_LTLU.o)
      _strmm_LTLN in libopenblas_sandybridgep-r0.2.8.a(strmm_LTLN.o)
      _strsm_LTUU in libopenblas_sandybridgep-r0.2.8.a(strsm_LTUU.o)
... some more of that, too
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libopenblas_sandybridgep-r0.2.8.dylib] Error 1
make[3]: *** [shared] Error 2

```

Your commit befa06fc9bae896e553b501e0f775d18055ee032 also changed the git version to head and added the buildem env, I tried several combinations to be sure, but it is always TARGET=SANDYBRIDGE that makes it fail. Without that, it builds fine here!

It seems that our processors are so different that OpenBLAS can correctly identify mine, but doesn't recognize yours. Did you try to set `TARGET=HASWELL`? That one works fine for me (found it here https://github.com/xianyi/OpenBLAS/issues/332).

What does the following command output for you?

```
$ sysctl -n machdep.cpu.brand_string
  Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
```

**Comment by chaubold** [comment]
And apparently with the latest (since some time in March) XCode updates, Objective-C doesn't support garbage collection any more which breaks VTK compilation. 

Can be fixed following these suggestions: http://permalink.gmane.org/gmane.comp.lib.vtk.user/72552,
which means adding the following line to vtk.cmake:

```
-DVTK_REQUIRED_OBJCXX_FLAGS=""
```

EDIT: I am not sure in how far removing that flag might break compilation on earlier OSX versions though!

**Comment by chaubold** [comment]
_(sorry I accidentally clicked the "Close&Comment" button instead of just "Comment"...)_

It all builds fine after addressing the VTK and OpenBLAS issues!

Before I merge the pull request: what do we do about the OpenBLAS target? If you do not specify any target, does it just build with warnings or does the build fail? I wouldn't know how to query the processor generation from within CMAKE, and I don't think it is our responsibility. An alternative might be to just document this behaviour in the buildem readme, and tell users to set `TARGET` explicitly by configuring the OpenBLAS build directly. 

I'm wondering whether this might be a problem only with your processor generation. Perhaps this will be fixed in OpenBLAS soon? Might be worth reporting?

**Comment by jakirkham** [comment]
Sorry to take a little while getting back to you so late. The last time I tried
Haswell it failed to build. The only one I had success with was 
TARGET=SANDYBRIDGE. However, I was still having issues with other parts of
buildem. I will double check and get back to you. Either way hardcoding
something like this is not the permanent solution as I am sure you
recognize.

As for the processor information. See below.

$ sysctl -n machdep.cpu.brand_string

Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz

**Comment by jakirkham** [comment]
I was having very serious issues with that version of XCode tools and
MATLAB. So, I actually downgraded. My XCode version is 5.0.2. My clang information is below.

As far as VTK is concerned, I don't know very much about how the library is
implemented, but it sounds like removing garbage collection should not
break it as it has support for manual reference counting. Correct?

$ clang --version

Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix

**Comment by jakirkham** [comment]
So, I retried TARGET=HASWELL. It seemed to build OpenBLAS. Maybe it also
has something to do with the release version. I will try to build
everything else and see if it completes successfully or not.

Since trying Haswell worked this time, I retried without any specification
(no TARGET flag) to make sure using the latest release doesn't also make
using the TARGET flag unnecessary. Building OpenBLAS has again succeeded.
In this case, I will again try building everything else and see if it
completes successfully or not.

Note: Not specifying TARGET does not result in the right architecture optimization. It will use Nehalem by default, which is undesirable for most people. They hadn't added Haswell to their list last time I looked, but most architectures supported are listed here ( https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt ). That being said it does appear that Haswell is now supported. Though, it is fairly recent ( https://github.com/xianyi/OpenBLAS/commit/26383708442569894c5fd3f14cdf1689f3300568 ), meaning after v0.2.8 the latest stable one that we have been using.

If leaving out the specification works, then I will write a commit to use
their most recent commit ( 4d42368214f2fd102b2d163c086e0f2d8c166dc6 ) instead
of HEAD and remove the TARGET flag.

It is probably worth noting that I downgraded XCode after getting buildem
to work.

**Comment by jakirkham** [comment]
Yes, we should document it and leave it out. See my other comment regarding
OpenBLAS.

Though, in the long run we will want to address the Qt flag issue (
Xarch_x86_64 ) in a more satisfactory way or at least determine how it
effects Mac users of older OSes.

**Comment by jakirkham** [comment]
Went ahead and removed OpenBLAS TARGET option and added commit SHA1 instead of HEAD. Also, added README_openblas.txt to spell out how to use TARGET and where to get more information.

**Comment by jakirkham** [comment]
When using TARGET=HASWELL or using default, they both built and completed successfully.

**Comment by jakirkham** [comment]
Added -DVTK_REQUIRED_OBJCXX_FLAGS="" to vtk.cmake with detailed comment in commit. Tested building VTK and it worked on my machine.

Built successfully to the end.

**Comment by chaubold** [comment]
Oh I did not notice that you were setting TARGET buildem-wide. I just added that flag to OpenBLAS. Is it possible that this caused your compile issues of Qt?

EDIT: now I also looked at the commits and not only your messages. As you only specified the target architecture for OpenBLAS as well, my question doesn't make sense any more.

**Comment by chaubold** [comment]
Good job! Glad to hear it built! 

I'll start cleaning up the commits of my branch so that we can merge this branch back to master at some point.

**Comment by jakirkham** [comment]
Yes, I had TARGET set for all at one point in time. I thought it would resolve other build issues after OpenBLAS that I was having at the time. That did have an undesirable effect on Qt.

If TARGET is just set for OpenBLAS, as you have noted, this problem does not occur.

**Comment by jakirkham** [comment]
Alright, sounds good.

**Pull request merged**
